### ISSUE TITLE
invalid args for command `save_document`: invalid type: integer `3`, expected string or map

### ISSUE THREAD

**Issue by 6543** [Calciumdibromid/CaBr2#546] opened 2021-05-17 17:32 UTC
**Describe the bug**
Can not save **cab2** file error msg: `invalid args for command `save_document`: invalid type: integer `3`, expected string or map`

**To Reproduce**
1. create new datasheet
2. add `bananenöl`
3. add `32`as Quantity with Unit `g` 
4. try to save

**Comment by 6543** [comment] 2021-05-17 17:32
tld: unit enum's are not matched correctly

**Comment by 6543** [comment] 2021-07-22 18:16
bug still exist!

**Comment by crapStone** [comment] 2021-09-12 16:11
could not reproduce, it probably was fixed with #649

**Closed by crapStone** 2021-09-12 16:11 UTC
Labels: kind/bug, reviewed
