### ISSUE TITLE
Add pipeline

### ISSUE THREAD

**Issue by crapStone** [Calciumdibromid/CaBr2#9] opened 2020-12-21 14:05 UTC
Add a pipeline to run angular and rust tests.

**Comment by 6543** [comment] 2020-12-21 14:07
I would call it CI ... yes we should add it.

I would take this, but it depends on adding a nice test suite ...

so blocked by #8 ?

**Comment by 6543** [comment] 2021-01-29 20:01
close as duplicate of #8

**Closed by 6543** 2021-01-29 20:01 UTC
Labels: help wanted, kind/build
