### ISSUE TITLE
make editing visible in the preview and on the pdf

### ISSUE THREAD

**Issue by kathi208** [Calciumdibromid/CaBr2#248] opened 2021-03-06 21:43 UTC
- [ ] It might be good to mark every changed detail with italic font on the pdf and in the preview
- [ ] add info in the line of sources what italic means

**Comment by crapStone** [comment] 2021-03-09 18:01
duplicate of #207?

**Comment by kathi208** [comment] 2021-03-11 01:04
No, there's a difference between an edited-symbol next to a chemical in the list underneath the search or a cursive text in the preview and on the pdf, when context has been changed.

**Closed** 2022-02-03 22:24 UTC
Labels: kind/feature, ui, reviewed, backend-crates
